SELECT CAST(id AS INT) AS movie_id,
TO_DATE("Release Date", 'YY-MM-DD') AS release_date,
"IMDB URL" AS imdb_url,
CAST(CAST("Film-Noir" AS INT) AS BOOLEAN) AS film_noir,
CAST(CAST("war" AS INT) AS BOOLEAN),
CAST(CAST("crime" AS INT) AS BOOLEAN),
CAST(CAST("drama" AS INT) AS BOOLEAN),
CAST(CAST("Action" AS INT) AS BOOLEAN) AS "action",
CAST(CAST("comedy" AS INT) AS BOOLEAN),
CAST(CAST("horror" AS INT) AS BOOLEAN),
CAST(CAST("Sci-fi" AS INT) AS BOOLEAN) AS scifi,
CAST(CAST("fantasy" AS INT) AS BOOLEAN),
CAST(CAST("musical" AS INT) AS BOOLEAN),
CAST(CAST("mystery" AS INT) AS BOOLEAN),
CAST(CAST("romance" AS INT) AS BOOLEAN),
CAST(CAST("western" AS INT) AS BOOLEAN),
CAST(CAST("unknown" AS INT) AS BOOLEAN),
CAST(CAST("thriller" AS INT) AS BOOLEAN),
CAST(CAST("adventure" AS INT) AS BOOLEAN),
CAST(CAST("animation" AS INT) AS BOOLEAN),
CAST(CAST("Children's" AS INT) AS BOOLEAN) AS children,
CAST(CAST("documentary" AS INT) AS BOOLEAN)
FROM {{ source('recommender_system_raw', 'movies')}}